#!/bin/bash
#Variable GITHUBNAME wird in .bashrc gesetzt 
GITHUB="curl https://github.com"
if [ "$#" -eq 0 ]; then 
	echo "$GITHUBNAME's public key"
	$GITHUB/$GITHUBNAME.keys
else    
	for NAME in "$@"
	do
		echo "$NAME's public key"
		$GITHUB/$NAME.keys
	done
fi



